### ISSUE TITLE
Updating a task with a modified projectId returns errors (Too many 500 error responses)

### ISSUE THREAD

**Issue by Vermoot** [lazeroffmichael/ticktick-py#18]
Hi!

I'm trying to use `TickTickClient.tasks.update()` to update a task, having modified its `projectId` property (I made sure many times that the project ID was correct), and I get some errors, making me unable to change the project of an existing task.

Here's what it looks like:

```
>>> hlo["projectId"]=tt.tt.get_by_fields(name="😇Rose")["id"]
>>> hlo
{'id': '61a7815f8f08107f4871e578', 'projectId': '61966f5c8f085532ae2ae930', 'sortOrder': -1099511627776, 'title': 'hello', 'timeZone': '', 'isFloating': False, 'reminder': '', 'reminders': [], 'priority': 0, 'status': 0, 'items': [], 'modifiedTime': '2021-12-01T14:06:23.299+0000', 'etag': 'f2ldu9ds', 'deleted': 0, 'createdTime': '2021-12-01T14:06:23.299+0000', 'creator': 118129146, 'tags': [], 'kind': 'TEXT'}
>>> tt.tt.task.update(hlo)
Traceback (most recent call last):
  File "/home/vermoot/Projects/notion-ticktick-bridge/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/vermoot/Projects/notion-ticktick-bridge/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/home/vermoot/Projects/notion-ticktick-bridge/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/home/vermoot/Projects/notion-ticktick-bridge/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/home/vermoot/Projects/notion-ticktick-bridge/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/vermoot/Projects/notion-ticktick-bridge/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ticktick.com', port=443): Max retries exceeded with url: /open/v1/task/61a7815f8f08107f4871e578 (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vermoot/Projects/notion-ticktick-bridge/venv/lib/python3.9/site-packages/ticktick/managers/tasks.py", line 244, in update
    response = self._client.http_post(url=url, json=task, headers=self.headers)
  File "/home/vermoot/Projects/notion-ticktick-bridge/venv/lib/python3.9/site-packages/ticktick/api.py", line 175, in http_post
    response = self._session.post(url, **kwargs)
  File "/home/vermoot/Projects/notion-ticktick-bridge/venv/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/vermoot/Projects/notion-ticktick-bridge/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vermoot/Projects/notion-ticktick-bridge/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/vermoot/Projects/notion-ticktick-bridge/venv/lib/python3.9/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.ticktick.com', port=443): Max retries exceeded with url: /open/v1/task/61a7815f8f08107f4871e578 (Caused by ResponseError('too many 500 error responses'))
>>>
```

**Comment by Vermoot** [comment]
Ah yeah, `move()` definitely looks like what I'm after for this. I worked around it by copying/deleting/re-creating the task with a different projectId, but that's a little janky. 

Thanks!
