### ISSUE TITLE
Getting 503 code when login

### ISSUE THREAD

**Issue by vibalcam** [lazeroffmichael/ticktick-py#25]
During the login process:

![image](https://user-images.githubusercontent.com/49537743/148989654-3c1d7403-1d60-4489-ba2c-75c420f6fc0a.png)

I am getting the following error:

![image](https://user-images.githubusercontent.com/49537743/148989597-7430be2e-c168-4560-ab16-37691fc2bca6.png)

When going deeper into the error. It looks like the login process is getting a 503 error. Any ideas on why it might be?

**Comment by broskees** [comment]
@lazeroffmichael also experiencing this issue..

**Comment by broskees** [comment]
@vibalcam & @EduardoCopat did either of you figure out a temporary workaround?

**Comment by lazeroffmichael** [comment]
@vibalcam @broskees @EduardoCopat 

For some reason, I am not able to reproduce the error. Would you guys be able to provide some more information such as the ticktick-py version you are using, python version, and which request it is failing at.

**Comment by EduardoCopat** [comment]
> @vibalcam @broskees @EduardoCopat
> 
> For some reason, I am not able to reproduce the error. Would you guys be able to provide some more information such as the ticktick-py version you are using, python version, and which request it is failing at.

Hello, @lazeroffmichael! First, thanks for this library :).

This is what I have installed:

```
Python 3.10.2
Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.11
idna               3.3
pip                21.2.4
pytz               2021.1
regex              2021.4.4
requests           2.26.0
setuptools         58.1.0
ticktick-py        2.0.2
urllib3            1.26.7
wheel              0.37.1
```

I am executing the code in a new PC (thus, I don't have the OAuth file). This is my simple script:

```
import os
import sys
import json
from ticktick.oauth2 import OAuth2        # OAuth2 Manager
from ticktick.api import TickTickClient   # Main Interface

# using get will return `None` if a key is not present rather than raise a `KeyError`
#print())

client = os.environ.get('TICKTICK_CLIENT_ID')
secret = os.environ.get('TICKTICK_CLIENT_SECRET')

import requests

requests_session = requests.session()

auth_client = OAuth2(client_id=client,
                     client_secret=secret,
                     redirect_uri='http://127.0.0.1:8080',
                      session=requests_session)

client = TickTickClient('xxxxx@gmail.com', os.environ.get('TICKTICK_PWD'), auth_client)

#print('fin')
#print()
f = open("tasks.txt", "w")
tasks = client.state['tasks']
f.write(json.dumps(tasks))
f.close()

sys.stdout.flush()
```

When I run the app, I am redirected to the following page:

![image](https://user-images.githubusercontent.com/2248490/153768376-7124e61e-5a71-4b8e-9ac5-a322b801e202.png)

Then I click allow and I'm redirected to this page:

`http://127.0.0.1:8080/?error=access_denied&error_description=User%20denied%20access&state=None`

Could it be something with the TickTick API? I'll try vibalcam suggestion above, maybe try to create another "app" at the TickTick API

**Comment by broskees** [comment]
I tried @vibalcam's solution, with a small differentiation in the `HEADERS` constant, then printed out the response codes in `http_get()` & `http_post()` - same issue as before.

`HEADERS` constant:
```python
    HEADERS = {
        'authority': 'api.ticktick.com',
        'sec-ch-ua': '" Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"',
        'x-device-user-agent': USER_AGENT,
        'x-requested-with': 'XMLHttpRequest',
        'sec-ch-ua-mobile': '?0',
        'content-type': 'application/json',
        'User-Agent': USER_AGENT,
        'sec-ch-ua-platform': '"Windows"',
        'accept': '*/*',
        'origin': 'https://ticktick.com',
        'sec-fetch-site': 'same-site',
        'sec-fetch-mode': 'cors',
        'sec-fetch-dest': 'empty',
        'referer': 'https://ticktick.com/',
        'accept-language': 'es,en-US;q=0.9,en;q=0.8'
    }
```

Console Output:
```
<Response [200]>
<Response [200]>
<Response [200]>
<Response [401]>
Traceback (most recent call last):
  File "/Users/josephroberts/localdev/task-sync-db/test.py", line 21, in <module>
    groceries = tt.task.create(local_task)   # Actually create the task
  File "/usr/local/lib/python3.9/site-packages/ticktick/managers/tasks.py", line 147, in create
    response = self._client.http_post(url=url, json=task, headers=self.oauth_headers)
  File "/usr/local/lib/python3.9/site-packages/ticktick/api.py", line 206, in http_post
    self.check_status_code(response, 'Could Not Complete Request')
  File "/usr/local/lib/python3.9/site-packages/ticktick/api.py", line 135, in check_status_code
    raise RuntimeError(error_message)
RuntimeError: Could Not Complete Request
```

**Comment by vibalcam** [comment]
> Lol, I tried deleting the `.token-oauth` file. @vibalcam's solution works now.

@broskees 
My bad, forgot to mention that after changing that I had to delete and recreate the .token-oauth. Not sure why to be honest.

**Comment by eduardocopat** [comment]
Unfortunately for me, @vibalcam solution did not work :(.

**Comment by vibalcam** [comment]
> Unfortunately for me, @vibalcam solution did not work :(.

Try to follow the steps I took:

1. Log into TickTick web and, using your browser's inspector, capture the http login request.
2. Copy the headers to a app capable of doing API calls (I used PostMan). The easiest way I found was to export the http request login and import it into Postman.
3. Test with Postman if it works
4. Export the headers to Python

**Comment by random25252** [comment]
> > Unfortunately for me, @vibalcam solution did not work :(.
> 
> Try to follow the steps I took:
> 
> 1. Log into TickTick web and, using your browser's inspector, capture the http login request.
> 2. Copy the headers to a app capable of doing API calls (I used PostMan). The easiest way I found was to export the http request login and import it into Postman.
> 3. Test with Postman if it works
> 4. Export the headers to Python

Appreciate the input on this. I have tried these steps but am still getting the similar access_denied response despite all attempted OAUTH2 variations on headers.

I have tried those headers and also my own from a successful authentication to the ticktick webapp:
    HEADERS = {'authority':'api.ticktick.com',
    'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36',
    'x-requested-with':'XMLHttpRequest',
    'x-device':'{"platform":"web","os":"Windows 10","device":"Chrome 98.0.4758.102","name":"","version":4120,"id":"62107006260b180c7e6b3554","channel":"website","campaign":"","websocket":""}',
    'content-type':'application/json',
    'accept':'*/*',
    'sec-gpc':'1',
    'origin':'https://ticktick.com',
    'sec-fetch-site':'same-site',
    'sec-fetch-mode':'cors',
    'sec-fetch-dest':'empty',
    'referer':'https://ticktick.com/'}

Wonder if you have any insight on other factors or code you changed to potentially successfully authenticate?

**Comment by vibalcam** [comment]
I forgot to mention that you have to regenerate `.token-oauth`. 

If it does not allow you to regenerate the token, make sure you the code in http_post and http_get to:
        if 'headers' not in kwargs:
            response = self._session.post(url, headers=self.HEADERS, **kwargs)
        else:
            kwargs['headers'].update(self.HEADERS)
            response = self._session.post(url, **kwargs)
        self.check_status_code(response, 'Could Not Complete Request')
    
        try:
            return response.json()
        except ValueError:
            return response.text

This just makes sure that no other headers were being used.

**Comment by random25252** [comment]
> I forgot to mention that you have to regenerate `.token-oauth`.
> 
> If it does not allow you to regenerate the token, make sure you the code in http_post and http_get to:
> 
> ```
>     if 'headers' not in kwargs:
>         response = self._session.post(url, headers=self.HEADERS, **kwargs)
>     else:
>         kwargs['headers'].update(self.HEADERS)
>         response = self._session.post(url, **kwargs)
>     self.check_status_code(response, 'Could Not Complete Request')
> 
>     try:
>         return response.json()
>     except ValueError:
>         return response.text
> ```
> 
> This just makes sure that no other headers were being used.

Hmm, not to be requesting support but interestingly I have no .token-oauth file generated, including a message in STDOUT that "Cache could not be read at: .token-oauth" which I had assumed was standard behavior if no valid token had been generated in past. If not, my issues may be differing. 

To note I also applied the code mentioned but again seem to be experiencing different behavior, when you authenticate in this manner, does the browser window correctly display the requested permissions and your username? As it does in the documentation but not for mine. Somehow suggesting my request may be malformed if this is the case.

**Comment by dkvdm** [comment]
This is still causing issues for me, anybody else experiencing similar login issues?

**Comment by chenyucheng0503** [comment]
> ```python
> Cache could not be read at: .token-oauth
> Enter the URL you were redirected to: http://127.0.0.1:8080/?code=BANANA&state=None
> Traceback (most recent call last):
>   File "/Users/dkvdm/Projects/portfolio/test.py", line 4, in <module>
>     auth_client = OAuth2(client_id="BANANANANANA",
>   File "/Users/dkvdm/.virtualenvs/portfolio/lib/python3.9/site-packages/ticktick/oauth2.py", line 136, in __init__
>     self.get_access_token(check_cache=check_cache, check_env=env_key)
>   File "/Users/dkvdm/.virtualenvs/portfolio/lib/python3.9/site-packages/ticktick/oauth2.py", line 311, in get_access_token
>     token_info = self._request_access_token()
>   File "/Users/dkvdm/.virtualenvs/portfolio/lib/python3.9/site-packages/ticktick/oauth2.py", line 225, in _request_access_token
>     token_info = self._post(self.OBTAIN_TOKEN_URL, params=payload)
>   File "/Users/dkvdm/.virtualenvs/portfolio/lib/python3.9/site-packages/ticktick/oauth2.py", line 249, in _post
>     raise RuntimeError("POST request could not be completed")
> RuntimeError: POST request could not be completed
> ```
> 
> This is still causing issues for me, anybody else experiencing similar login issues?

got the same `POST request could not be completed` Error. Have you fix it ?
