### ISSUE TITLE
Cache file wont download

### ISSUE THREAD

**Issue by FusionPeep** [lazeroffmichael/ticktick-py#30]
I tried to initialize client just as described in documentation of this library. I got to the point of pop up browser screen and redirect uri. After inserting the URL from browser, I received below mentioned error and no .oath file is created. I tripple checked the credentials and all 15 lines of code, didn't find any typos. Could someone help me with this issue? I'd be very grateful for any help. 

Enter the URL you were redirected to: http://127.0.0.1:8080/?code=ZZlkTW&state=None
Traceback (most recent call last):
  File "/Users/prosto/Documents/Ticktcik APP/initialize.py", line 10, in <module>
    oauth = OAuth2(client_id=clientId,
  File "/usr/local/lib/python3.9/site-packages/ticktick/oauth2.py", line 136, in __init__
    self.get_access_token(check_cache=check_cache, check_env=env_key)
  File "/usr/local/lib/python3.9/site-packages/ticktick/oauth2.py", line 311, in get_access_token
    token_info = self._request_access_token()
  File "/usr/local/lib/python3.9/site-packages/ticktick/oauth2.py", line 225, in _request_access_token
    token_info = self._post(self.OBTAIN_TOKEN_URL, params=payload)
  File "/usr/local/lib/python3.9/site-packages/ticktick/oauth2.py", line 249, in _post
    raise RuntimeError("POST request could not be completed")
RuntimeError: POST request could not be completed

**Comment by chenyucheng0503** [comment]
Got the totally same question and the client can't be initialized. Have you fix it ?
