### ISSUE TITLE
405 Method not allowed

### ISSUE THREAD

**Issue by dolphikcode** [lazeroffmichael/TickTick-py#56]
Hi,
I was going through readme, got token, but client = TickTickClient(username, password, auth_client) gives me such errors:

```
Traceback (most recent call last):
  File "/home/dolph/PycharmProjects/hq-new-api/tick.py", line 14, in <module>
    client = TickTickClient(username, password, auth_client)
  File "/home/dolph/PycharmProjects/hq-new-api/venv/lib/python3.10/site-packages/ticktick/api.py", line 52, in __init__
    self._prepare_session(username, password)
  File "/home/dolph/PycharmProjects/hq-new-api/venv/lib/python3.10/site-packages/ticktick/api.py", line 67, in _prepare_session
    self._login(username, password)
  File "/home/dolph/PycharmProjects/hq-new-api/venv/lib/python3.10/site-packages/ticktick/api.py", line 104, in _login
    response = self.http_post(url, json=user_info, params=parameters, headers=self.HEADERS)
  File "/home/dolph/PycharmProjects/hq-new-api/venv/lib/python3.10/site-packages/ticktick/api.py", line 184, in http_post
    response = self._session.post(url, **kwargs)
  File "/home/dolph/PycharmProjects/hq-new-api/venv/lib/python3.10/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/dolph/PycharmProjects/hq-new-api/venv/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dolph/PycharmProjects/hq-new-api/venv/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/dolph/PycharmProjects/hq-new-api/venv/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.ticktick.com', port=443): Max retries exceeded with url: /api/v2/user/signin?wc=True&remember=True (Caused by ResponseError('too many 405 error responses'))
```

**Comment by DougX71** [comment]
I had another attempt at getting the API to work.  On June 19, 2023, I reported getting the 'too many 500 error responses error at #26 . Recently I applied the updates to go to v2.0.2 and now get the same 'too many 405 error responses' error in a source code line equivalent to what @dolphikcode reports.

**Comment by dolphikcode** [comment]
I have made changes mentioned in #55  (code below) and now am at "too many 500 error responses". Will wait until tomorrow to check if maybe anything change

```    USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0"
    X_DEVICE_ = '{"platform":"web","os":"OS X","device":"Firefox 123.0","name":"unofficial api!","version":4531,' \
                '"id":"6490' + secrets.token_hex(10) + '","channel":"website","campaign":"","websocket":""}'

    HEADERS = {'User-Agent': USER_AGENT,
               'x-device': X_DEVICE_}
```

@DougX71 I tried change in http_post method, but still nothing

Follow up: account is blocked for 24 hours... "Sorry, your account has been restricted from login. Please try again after 24 hours, or click "Forgot Password" to reset."

**Comment by DougX71** [comment]
I made a similar change to api.pi too .
In api.py, I replaced these 2 lines:
`USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0"
X_DEVICE_ = '{"platform":"web","os":"OS X","device":"Firefox 95.0","name":"unofficial api!","version":4531,' 
` 
with these 2:
`USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0"
X_DEVICE_ = '{"platform":"web","os":"OS X","device":"Firefox 123.0","name":"unofficial api!","version":4531,' \
`
I still got the 'too many 405 error responses' error.
I am relatively inexperienced with Python and wondered about using a USER_AGENT string that says I have a Mac and Firefox when I am running Windows.  I did some searching online and found this code to get my actual user agent:
`from selenium import webdriver

driver = webdriver.Chrome()
user_agent = driver.execute_script("return navigator.userAgent")
driver.quit()`

Based on what code retrieved, I changed my USER_AGENT string to this:
`USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"`

But it didn’t make any difference.

**Comment by dolphikcode** [comment]
@DougX71 
1. I stopped to have 405 error after changing line 94 in api.py to: `url = self.BASE_URL + 'user/signon'` as in #55 (and started to get 500 error, but still could log in into ticktick website) 
2. I set USER_AGENT and X_DEVICE for Firefox 123.0
3. I changed http_post the way @edbock did in last comment in #26 and then followed his points
4. I changed password because TickTick blocked me and now it's working correctly
Hope this helps...

**Comment by DougX71** [comment]
Thanks for your suggestions @dolphikcode .  I thought I made the changes correctly but am still getting the 'too many 405 error responses' error.  Would you please attach the api.py you are using so that I can run the exact same version? 

**Update**: I downloaded the version of api.py I found in https://github.com/lazeroffmichael/ticktick-py/pull/55 by [zozzzC](https://github.com/zozzzC).   I still got the the 'too many 405 error responses' error but subsequently realized that I had made a mistake and downloaded the "before" version from GitHub.  When I downloaded the correct version from https://github.com/lazeroffmichael/ticktick-py/pull/55 it worked.

Later I realized that when testing your changes that I inadvertently modified the wrong version of api.py.
When I looked for api.py on my laptop I found it in 
`F:\Inspiron copy\Doug\TickTickAPIUsage\venv\Lib\site-packages\ticktick` and modified that version.
But the version that was being run was in 
`C:\Program Files (x86)\Python39-32\Lib\site-packages\ticktick`
So, when I copied the version of api.py with your changes to the right folder, it worked.
I noticed that although the  [zozzzC](https://github.com/zozzzC) version is missing the changes to http_post that it works anyway.

**Comment by random25252** [comment]
This worked for me if you don't want to modify the api.py file directly. Place this code before the client initialisation. Let me know if this worked for you guys but yeah did the trick in my case:

```
USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0"
X_DEVICE_ = '{"platform":"web","os":"OS X","device":"Firefox 123.0","name":"unofficial api!","version":4531,' \


def new_login(self, username, password):
    url = self.BASE_URL + 'user/signon?wc=true&remember=true'
    user_info = {
        'username': username,
        'password': password,
    }
    parameters = {
        'wc': True,
        'remember': True
    }

    response = self.http_post(url, json=user_info, params=parameters, headers=self.HEADERS)
    print(response)
    self.access_token = response['token']
    self.cookies['t'] = self.access_token

TickTickClient._login = new_login

```

I believe this is called monkey patching

**Comment by edbock** [comment]
I'm back again after getting 'too many 405 error responses' just now. I applied @random25252's solution above and it immediately fixed the issue for me.

Special thanks to @lazeroffmichael for providing this library and to everyone here who has contributed workarounds for these errors.

**Comment by dolphikcode** [comment]
Thanks @random25252 for the patch, works as charm. 

Just regarding `user/signon?wc=true&remember=true` I have deleted everything after signon as later in the code you have
```
parameters = {
        'wc': True,
        'remember': True
    }
```
which is doubling the parameters in request...

**Comment by luutuankiet** [comment]
thanks @random25252 worked as charm to fix the issue "too many 405 error responses". 
For my further understanding could you or someone here help provide some context on why the code change worked ? Is it because of a conflict in the way TickTickClient's login method ? 
Because this fix doesn't quite match my understanding of the issue - all err 405 reported issues in this repo is related to TickTick's anti fraud measures which introduced a CAPTCHA in login step if your app exceed their defined threshold.

**Comment by DougX71** [comment]
@luutuankiet 
In #55 @zozzzC reported that user/signin doesn't work anymore and user/signon must be used instead.

But I wonder about the API integration products like Pipedream and Zapier.  If the signin/signon procedure changed, wouldn't TickTick update some documenation on this?

Before I applied @zozzzC's fix I was getting the 'too many 405 error responses' error without any CAPTCHA prompts.
